- name: Setup host
  hosts: mpd
  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.package:
        name:
          - mpd
          - mpc
          - alsa-utils
          - ladspa-sdk
          - libfftw3-dev
          - libiniparser-dev
          - libasound2-dev
          - libsndfile1-dev
          - libtool
          - wmctrl
          - x11-utils
          - feh
          - matchbox-window-manager
          - rxvt-unicode
          - cava
          - xbindkeys
          - xosd-bin
          - xfonts-100dpi
          - xfonts-75dpi
          - xfonts-base
          - python3-pip
          - python3-requests
          - python3-evdev
          - python3-systemd
          - bind9-host
          - vim
          - command-not-found
          - jq
        state: present

    - name: Remove unwanted packages
      become: true
      ansible.builtin.package:
        name:
          - modemmanager
        state: absent


    - name: Add snd-aloop to modules.load.d
      become: true
      ansible.builtin.copy:
        src: files/snd-aloop.conf
        dest: /etc/modules-load.d/snd-aloop.conf
        mode: "0644"

    - name: Set dtparam=audio=off
      become: true
      ansible.builtin.lineinfile:
        dest: /boot/firmware/config.txt
        regexp: '^dtparam=audio='
        line: 'dtparam=audio=off'
        state: present

    - name: Enable gpio-shutdown overlay
      become: true
      ansible.builtin.lineinfile:
        dest: /boot/firmware/config.txt
        regexp: '^dtoverlay=gpio-shutdown'
        line: 'dtoverlay=gpio-shutdown,gpio_pin=17,active_low=1,gpio_pull=up'
        state: present

    - name: Enable gpio-poweroff overlay
      become: true
      ansible.builtin.lineinfile:
        dest: /boot/firmware/config.txt
        regexp: '^dtoverlay=gpio-poweroff'
        line: 'dtoverlay=gpio-poweroff,gpio_pin=18'
        state: present

    - name: Mask man-db timer
      become: true
      ansible.builtin.systemd:
        name: man-db.timer
        masked: true
        state: stopped

    - name: Mask apt-daily timers
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        state: stopped
      loop:
        - apt-daily.timer
        - apt-daily-upgrade.timer
