[general]
stereo = true
autosens = 1
sensitivity = 4
bars = 128

[input]
method = alsa
source = cava_capture

[output]
method = raw
data_format = ascii
ascii_max_range = 255

[smoothing]
gravity = 150
monstercat = 0
waves = 0
noise_reduction = 15
