KEY_PLAYPAUSE    1   mpc toggle
KEY_PAUSE        1   mpc toggle
KEY_STOPCD       1   mpc stop
KEY_NEXTSONG     1   mpc next
KEY_PREVIOUSSONG 1   mpc prev
KEY_FASTFORWARD 1   mpc seek +0:0:30  # Seek forward by 30 seconds
KEY_REWIND      1   mpc seek -0:0:30  # Seek backward by 30 seconds
KEY_VOLUMEUP    1   mpc volume +5
KEY_VOLUMEDOWN  1   mpc volume -5
