#!/bin/bash
set -x  # optional, shows commands as they run

# Disable screensaver / power management
xset s off
xset -dpms
xset s noblank
xbindkeys &
unclutter -idle 1 &

# Start MPD watcher script
systemd-cat -t mpd_watch python3 "$HOME/mpd_watch.py" &

# Start minimal WM
matchbox-window-manager -use_titlebar no