#!/bin/bash
set -x  # optional, shows commands as they run

# Disable screensaver / power management
xset s off
xset -dpms
xset s noblank
xbindkeys &
unclutter -idle 1 &

# Start MPD controller
systemd-cat -t mpd-controller $HOME/mpd-controller-arm64

# Start minimal WM
matchbox-window-manager -use_titlebar no