#!/bin/bash
exec >"$HOME/kiosk.log" 2>&1
set -x  # optional, shows commands as they run

# Disable screensaver / power management
xset s off
xset -dpms
xset s noblank
xbindkeys
unclutter -idle 1 &

# Start MPD watcher script
python3 "$HOME/mpd_watch.py" 2>&1 &

# Start minimal WM
matchbox-window-manager -use_titlebar no